# Generated by Django 4.1.5 on 2023-08-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groceries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grocery_name', models.CharField(max_length=30)),
                ('gram', models.IntegerField()),
                ('calorie', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_choice', models.CharField(choices=[('lose_weight', 'lose_weight'), ('maintain', 'maintain_weight'), ('build_muscle', 'build_muscle')], max_length=20)),
                ('start_weight', models.FloatField()),
                ('goal_weight', models.FloatField()),
                ('week_goal', models.IntegerField()),
                ('calorie_goal', models.IntegerField()),
                ('activity', models.CharField(choices=[('moderate', 'moderate'), ('very_high', 'very_high'), ('high', 'high'), ('low', 'low')], max_length=20)),
                ('nutritional_goal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=250)),
                ('image', models.URLField(max_length=2500)),
            ],
        ),
    ]
