# Generated by Django 4.1.5 on 2023-08-06 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0003_rename_goal_choice_profile_your_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_choice', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GoalChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_choice', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='week_goal',
            new_name='week_goal_to_lose_or_gain',
        ),
        migrations.AlterField(
            model_name='profile',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caloriecounter.activitychoices'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='your_goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caloriecounter.goalchoices'),
        ),
    ]
