# Generated by Django 4.1.5 on 2023-08-06 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0004_activitychoices_goalchoices_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutritional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macronutrient', models.CharField(max_length=20)),
                ('percentage', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='nutritional_goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caloriecounter.nutritional'),
        ),
    ]
