# Generated by Django 4.1.5 on 2023-08-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0005_nutritional_alter_profile_nutritional_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritional',
            name='macronutrient',
        ),
        migrations.AddField(
            model_name='nutritional',
            name='carbs',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AddField(
            model_name='nutritional',
            name='fett',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AddField(
            model_name='nutritional',
            name='protein',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
