# Generated by Django 4.1.5 on 2023-08-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0006_remove_nutritional_macronutrient_nutritional_carbs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritional',
            name='percentage',
        ),
        migrations.AlterField(
            model_name='nutritional',
            name='carbs',
            field=models.IntegerField(default=40, max_length=20),
        ),
        migrations.AlterField(
            model_name='nutritional',
            name='fett',
            field=models.IntegerField(default=30, max_length=20),
        ),
        migrations.AlterField(
            model_name='nutritional',
            name='protein',
            field=models.IntegerField(default=30, max_length=20),
        ),
    ]
