# Generated by Django 4.1.5 on 2023-08-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0007_remove_nutritional_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritional',
            name='total',
            field=models.IntegerField(default=100, max_length=20),
        ),
    ]
