# Generated by Django 4.1.5 on 2023-08-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0008_nutritional_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='carbs',
            field=models.IntegerField(default=40, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='fett',
            field=models.IntegerField(default=30, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='protein',
            field=models.IntegerField(default=30, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='total',
            field=models.IntegerField(default=100, max_length=20),
        ),
    ]
