# Generated by Django 4.1.5 on 2023-08-12 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0009_profile_carbs_profile_fett_profile_protein_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbs', models.IntegerField(default=40)),
                ('protein', models.IntegerField(default=30)),
                ('fett', models.IntegerField(default=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='fett',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nutritional_goal',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total',
        ),
        migrations.DeleteModel(
            name='Nutritional',
        ),
        migrations.AddField(
            model_name='profile',
            name='nutrition_goal',
            field=models.ForeignKey(default=1500, on_delete=django.db.models.deletion.CASCADE, to='Caloriecounter.nutrition'),
        ),
    ]
