# Generated by Django 4.1.5 on 2023-10-23 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0010_nutrition_remove_profile_carbs_remove_profile_fett_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutrition',
            old_name='fett',
            new_name='fat',
        ),
    ]
