# Generated by Django 4.1.5 on 2023-11-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0012_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groceries',
            old_name='gram',
            new_name='grams',
        ),
        migrations.AddField(
            model_name='groceries',
            name='dietary_fibers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groceries',
            name='saturated_fet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groceries',
            name='sodium',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groceries',
            name='sugars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groceries',
            name='total_carbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groceries',
            name='total_fet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groceries',
            name='total_protein',
            field=models.IntegerField(default=0),
        ),
    ]
