# Generated by Django 4.1.5 on 2023-11-01 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0013_rename_gram_groceries_grams_groceries_dietary_fibers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groceries',
            new_name='G',
        ),
    ]
