# Generated by Django 4.1.5 on 2023-11-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0014_rename_groceries_g'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='G',
            new_name='Grocery',
        ),
    ]
