# Generated by Django 4.1.5 on 2023-11-03 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0015_rename_g_grocery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='week_goal_to_lose_or_gain',
            new_name='week_goal',
        ),
    ]
