# Generated by Django 4.1.5 on 2023-11-04 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0018_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipes',
        ),
    ]
