# Generated by Django 4.1.5 on 2023-11-05 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0023_nutrition_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
