# Generated by Django 4.1.5 on 2023-11-05 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0024_alter_nutrition_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrition',
            name='user',
        ),
    ]
