# Generated by Django 4.1.5 on 2023-11-08 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0025_remove_nutrition_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grocery',
            old_name='saturated_fet',
            new_name='saturated_fat',
        ),
        migrations.RenameField(
            model_name='grocery',
            old_name='total_fet',
            new_name='total_fat',
        ),
    ]
