# Generated by Django 4.1.5 on 2023-11-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0026_rename_saturated_fet_grocery_saturated_fat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='dietary_fibers',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='saturated_fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='sodium',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='sugars',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='total_carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='total_fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='total_protein',
            field=models.FloatField(default=0),
        ),
    ]
