# Generated by Django 4.1.5 on 2023-11-09 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0027_alter_grocery_dietary_fibers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=10)),
                ('groceries', models.ManyToManyField(to='Caloriecounter.grocery')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caloriecounter.profile')),
            ],
        ),
    ]
