# Generated by Django 4.1.5 on 2023-11-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0030_profile_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dates',
            field=models.DateField(),
        ),
    ]
