# Generated by Django 4.1.5 on 2023-11-11 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0031_alter_profile_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dates',
        ),
    ]
