# Generated by Django 4.1.5 on 2023-11-12 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0032_remove_profile_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealGrocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.FloatField(default=100)),
                ('updated_calorie', models.FloatField(default=0)),
                ('grocery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caloriecounter.grocery')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Caloriecounter.meal')),
            ],
        ),
    ]
