# Generated by Django 4.1.5 on 2023-11-12 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0033_mealgrocery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='date',
        ),
    ]
