# Generated by Django 4.1.5 on 2023-11-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0034_remove_meal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealgrocery',
            name='updated_dietary_fibers',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mealgrocery',
            name='updated_saturated_fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mealgrocery',
            name='updated_sodium',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mealgrocery',
            name='updated_sugars',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mealgrocery',
            name='updated_total_carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mealgrocery',
            name='updated_total_fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mealgrocery',
            name='updated_total_protein',
            field=models.FloatField(default=0),
        ),
    ]
