# Generated by Django 4.1.5 on 2023-11-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0035_mealgrocery_updated_dietary_fibers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='date',
            field=models.DateField(default=0),
        ),
    ]
