# Generated by Django 4.1.5 on 2023-11-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0038_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='week_goal',
        ),
    ]
