# Generated by Django 4.1.5 on 2023-11-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0039_remove_profile_week_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='steps',
            field=models.IntegerField(default=0),
        ),
    ]
