# Generated by Django 4.1.5 on 2023-11-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0040_profile_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='steps',
            field=models.IntegerField(),
        ),
    ]
