# Generated by Django 4.1.5 on 2023-11-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0044_alter_steps_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='date',
            field=models.DateField(default=True),
        ),
    ]
