# Generated by Django 4.1.5 on 2023-11-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0046_successstories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='goal_weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='start_weight',
            field=models.IntegerField(),
        ),
    ]
