# Generated by Django 4.1.5 on 2023-11-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0047_alter_profile_goal_weight_alter_profile_start_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(help_text='Use line breaks to separate ingredients.'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(help_text='<br><br>'),
        ),
    ]
