# Generated by Django 4.1.5 on 2023-11-29 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0048_alter_recipe_ingredients_alter_recipe_instructions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='successstories',
            old_name='image_url',
            new_name='image_url_success',
        ),
    ]
