# Generated by Django 4.1.5 on 2023-11-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0049_rename_image_url_successstories_image_url_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='successstories',
            name='description',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='successstories',
            name='title_success',
            field=models.CharField(default=0, max_length=24),
        ),
    ]
