# Generated by Django 4.1.5 on 2023-11-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0050_successstories_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successstories',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='successstories',
            name='title_success',
            field=models.CharField(max_length=24),
        ),
    ]
