# Generated by Django 4.1.5 on 2023-12-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0051_alter_successstories_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealgrocery',
            name='grams',
        ),
        migrations.AddField(
            model_name='mealgrocery',
            name='updated_grams',
            field=models.IntegerField(default=100),
        ),
    ]
