# Generated by Django 4.2.19 on 2025-09-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caloriecounter', '0052_remove_mealgrocery_grams_mealgrocery_updated_grams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealgrocery',
            name='updated_grams',
            field=models.IntegerField(),
        ),
    ]
